## Develop your own cheatsheet taking notes during the course

You can either do it here or in Notion, if you want guidance for it you can rewatch the class taken by Umut about note taking https://strive-school.zoom.us/rec/share/bKqjQrgxpTljao75kpoesMafGtzQcwFtXuWqSVTOvuoO36i0b1pDTtVOK1RbwHRa.00z2B3Y_wtvKKbMA.

It is convenient to have short notes with definitions, and an example with a snippet of code.

Example:

## 1. Norm of a vector - Magnitude

$$ v = (v_{1}, v_{2}, ...,v_{n})$$

$$ ||v|| = \sqrt{v_{1}^{2}+v_{2}^{2} + ... + v_{n}^{2}}$$

In [2]:
import numpy as np
import math
v = np.array([1,2,3,4])
v_norm = np.linalg.norm(v)
v_norm

5.477225575051661

## 2. Vector - Addition - Subtraction - Multiplication - Division

In [51]:
u = np.array([1, 2, 1])
v = np.array([1, 4, 3])

print(u + v)
print(10 * u)

[2 6 4]
[10 20 10]


## 3. Dot Product = scalar product = inner product = projection product
## [a,b,c] * [x,y,z] = a*x +b*y + c*z

In [49]:
t = np.dot(u, v)
print(t)

12


## 4. Angle between 2 vectors given the dot product

In [57]:
u = np.array([1, 2])
v = np.array([-2, 1])
origin = np.array([0 ,0])

dot_product_uv = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

cos_theta = dot_product_uv / (norm_u * norm_v)

theta_radians = np.arccos(cos_theta)
theta_degrees = theta_radians * 180 / np.pi
print(theta_degrees)

import matplotlib.pyplot as plt
# plt.quiver(origin, origin, u, v, scale=21)


90.0


## 5. Matrix
## np.add(), np.subtract(), np.multiply() / np.matmul(), np.divide()

In [91]:
m = np.mat([[1, 2, 3], [4, 5, 6]])
n = np.mat([[1, 2, 3], [4, 5, 6]])

print(m, '\n', n)
np.multiply(m, n)
print()
print(m, '\n', np.transpose(n))
np.matmul(m, np.transpose(n))

[[1 2 3]
 [4 5 6]] 
 [[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]] 
 [[1 4]
 [2 5]
 [3 6]]


matrix([[14, 32],
        [32, 77]])

## 6. Add a column to a matrix

In [78]:
n = [[3, 2, 5], [1, 4, 7]]

def add_column(matrix):
  i = np.mat(matrix)
  a,b = i.shape
  j = np.zeros((a, 1))
  x = np.hstack((i, j))
  return x

add_column(n)

matrix([[3., 2., 5., 0.],
        [1., 4., 7., 0.]])

## 7. Add a row to a matrix

In [85]:
m = [[0, 0], [0, 0]]
n = [[3, 2, 5], [1, 4, 7]]

def add_row(matrix):
  new_row = np.zeros(len(matrix[0]))
  x = np.vstack([matrix, new_row])
  return x

print(add_row(m))
print(m)
print(add_row(n))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0, 0], [0, 0]]
[[3. 2. 5.]
 [1. 4. 7.]
 [0. 0. 0.]]


## 8. Transpose a matrix

In [82]:
def transpose(m):
    return np.transpose(m)

m = [[3, 4, 6], [1, 5, 9]]
transpose(m)

array([[3, 1],
       [4, 5],
       [6, 9]])

## 9. Calculate the magnitude of an n-dimensional vector

In [4]:
def magnitude_complete(v):
    vector = np.array(v)
    return np.linalg.norm(vector)
magnitude_complete([1,2,3,4])

5.477225575051661

## 10. Calculate the magnitude of 2 vectors (a + b)

In [9]:
def magnitude_vectors(a, b):
    if a == b:
        pass
    else:
        return (np.linalg.norm(a+b))
magnitude_vectors([5,2,4],[1,2,4])

8.12403840463596

## 11. Inverse a matrix

In [12]:
a = np.array([[1, 2, 3], [1, 3, 3], [1, 2, 4]])
ainv = np.linalg.inv(a)
print(ainv)

[[ 6. -2. -3.]
 [-1.  1.  0.]
 [-1.  0.  1.]]


### 12. 

### 13. 

### 14. 

### 15. 

### 16. 

### 17. 