## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
import numpy as np
import math

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [3]:
# okay numpy is great but... how would you inverse a matrix by hand?
a = [[3,1,2], [-5,4,1], [0,3,-8]]
b = [[0,5,-1], [3,2,-1], [10,0.5,4]]
inverse = np.linalg.inv(a)
print(inverse)
# def inverse_matrix(A):

#     return ""

[[ 0.2        -0.08        0.04      ]
 [ 0.22857143  0.13714286  0.07428571]
 [ 0.08571429  0.05142857 -0.09714286]]


![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [18]:
# Just answer using code --> easy stuff!
a = np.array([[3,0.6,4,-3], [-1.3,4,0,8.6], [7,0,-8,0.006]])
b = np.array([[3,-5.76,45,0],[2,-2,1.3,9], [-9,0,0,0]])
c = np.array([[0,1009,-66.7849,90], [0,5,4,-0.07], [-7.7,0,0,0]])
d = a+b-c
print(d)
print(d[1,2])
print(d[2,0])
# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

[[ 6.000000e+00 -1.014160e+03  1.157849e+02 -9.300000e+01]
 [ 7.000000e-01 -3.000000e+00 -2.700000e+00  1.767000e+01]
 [ 5.700000e+00  0.000000e+00 -8.000000e+00  6.000000e-03]]
-2.7
5.7


![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [31]:
a = np.array([0.6,-15,2,5,98])
b = np.array([[2,2,-4], [9,-14,0], [13,-0.5,44], [1,9,4], [0,0,5]])
c = np.matmul(a,b)
print(c)
print(c.shape)
print(c[2])


[-102.8  255.2  595.6]
(3,)
595.6
