# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [128]:
import numpy as np
def add_vectors(u, v):
  return np.array(u) + np.array(v)

a = [1, 2, 3]
b = [1, 1, 1]
add_vectors(a, b)

array([2, 3, 4])

Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [140]:
def scalar_mult(s, v):
    return s * np.array(v)

a = [1, 2, 3]
scalar_mult(4, a)

array([ 4,  8, 12])

Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [27]:
def dot_product(u, v):
  t = np.array(u) * np.array(v)
  return sum(t)

dot_product([1, 2, 1], [1, 4, 3])

12

## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [171]:
from copy import deepcopy
def copy_matrix(matrix):
  x = np.mat(matrix)
  x1 = deepcopy(x)
  return x1

# copy_matrix([[1, 2], [3, 4]])
# copy_matrix([[1, 2, 3], [4, 5, 6]])
# copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])

m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
print(m)
copyofm = copy_matrix(m)
print(copyofm)
for row_num, row in enumerate(copyofm):
  for col_num, col_val in enumerate(row):
    copyofm[row_num][col_num] = 42

print(copyofm)
print(m)

[[1, 0, 0], [0, 2, 0], [0, 0, 3]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[42 42 42]
 [42 42 42]
 [42 42 42]]
[[1, 0, 0], [0, 2, 0], [0, 0, 3]]


In [182]:
m = [[0, 0], [0, 0]]
n = [[3, 2, 5], [1, 4, 7]]

def add_row(matrix):
  new_row = np.zeros(len(matrix[0]))
  x = np.vstack([matrix, new_row])
  return x

print(add_row(m))
print(m)
print(add_row(n))

      # >>> m = [[0, 0], [0, 0]]
      # >>> add_row(m)
      # [[0, 0], [0, 0], [0, 0]]
      # >>> n = [[3, 2, 5], [1, 4, 7]]
      # >>> add_row(n)
      # [[3, 2, 5], [1, 4, 7], [0, 0, 0]]
      # >>> n
      # [[3, 2, 5], [1, 4, 7]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0, 0], [0, 0]]
[[3. 2. 5.]
 [1. 4. 7.]
 [0. 0. 0.]]


In [183]:
m = [[0, 0], [0, 0]]
n = [[3, 2, 5], [1, 4, 7]]

def add_column(matrix):
  i = np.mat(matrix)
  a,b = i.shape
  j = np.zeros((a, 1))
  x = np.hstack((i, j))
  return x

add_column(n)
# print(n)
      # >>> m = [[0, 0], [0, 0]]
      # >>> add_column(m)
      # [[0, 0, 0], [0, 0, 0]]
      # >>> n = [[3, 2], [5, 1], [4, 7]]
      # >>> add_column(n)
      # [[3, 2, 0], [5, 1, 0], [4, 7, 0]]
      # >>> n
      # [[3, 2], [5, 1], [4, 7]]

matrix([[3., 2., 5., 0.],
        [1., 4., 7., 0.]])

Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [119]:
def add_matrices(m1, m2):
  return np.add(m1, m2)

a = [[1, 2], [3, 4]]
b = [[2, 2], [2, 2]]
add_matrices(a, b)
      # [[3, 4], [5, 6]]
c = [[8, 2], [3, 4], [5, 7]]
d = [[3, 2], [9, 2], [10, 12]]
add_matrices(c, d)
      # [[11, 4], [12, 6], [15, 19]]

array([[11,  4],
       [12,  6],
       [15, 19]])

Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [162]:
def scalar_mult(s, m):
  return np.multiply(s, m)

a = [[1, 2], [3, 4]]
scalar_mult(3, a)
      # [[3, 6], [9, 12]]
b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
scalar_mult(10, b)
scalar_mult([[1, 2], [3, 4]], [[5, 6], [7, 8]])
      # [[30, 50, 70], [10, 10, 10], [0, 20, 0], [20, 20, 30]]

70

Write functions row_times_column and matrix_mult:

In [180]:
def row_times_column(m1, row, m2, column):
    res = np.matmul(m1, m2)
    return res[row][column]

row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)

    #   >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
    #   19
    #   >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
    #   22
    #   >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
    #   43
    #   >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)
    #   50

22

In [181]:
def matrix_mult(m1, m2):
    res = np.matmul(m1, m2)
    return res

matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])


      # >>> matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
      # [[19, 22], [43, 50]]
      # >>> matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
      # [[31, 19], [85, 55]]
      # >>> matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])
      # [[39, 54, 69], [13, 23, 33], [14, 19, 24]]

array([[19, 22],
       [43, 50]])

Write a function transpose that takes a matrix as an argument and returns is transpose:

In [170]:
def transpose(m):
    return np.transpose(m)

# m = [[3, 4, 6], [1, 5, 9]]
# transpose(m)
m = [[3, 4, 6]]
transpose(m)
#      [[3], [4], [6]]
#      >>> m
#      [3, 4, 6]
#      >>> m = [[3, 4, 6], [1, 5, 9]]
#      >>> transpose(m)
#      [[3, 1], [4, 5], [6, 9]]

array([[3],
       [4],
       [6]])