# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [9]:
import numpy as np
print(np.__version__)
np.show_config

1.21.2


<function numpy.__config__.show()>

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [13]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [14]:
z = np.zeros((10,10))
size = z.size * z.itemsize
print(size)

800


8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [17]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [20]:
#np.full creates a vector of the size in the first tuple, and of value in the second argument
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [22]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [25]:
z = np.arange(50, 10, -1)
print(z)
print(z[::-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [26]:
z = np.arange(9)
print(z.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [27]:
z = np.array([1,2,0,0,4,0])
print(z.nonzero())

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [30]:
z = np.eye(3,3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [38]:
z= np.random.random((3,3,3))
print(z)

[[[0.55973288 0.42232838 0.18878572]
  [0.21746918 0.35183471 0.3800963 ]
  [0.35589404 0.58377875 0.06894725]]

 [[0.90978675 0.05188289 0.01956022]
  [0.62589471 0.16266973 0.16750689]
  [0.36342982 0.46990133 0.10644779]]

 [[0.77177908 0.66845906 0.2346581 ]
  [0.68786984 0.63525755 0.15361963]
  [0.91219684 0.41634231 0.16319841]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [43]:
z = np.random.random((10,10))
minn = z.min()
print(minn)
maxx = z.max()
print(maxx)

0.011624095194612605
0.9900459874806485


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [45]:
z = np.random.random(30)
print(z.mean())

0.5106049596187028


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [48]:
z=np.ones((5,5))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [50]:
z=np.ones((5,5))
z=np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [98]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 0.1 *3)

nan
False
False
nan
True
False


nan
False
False
nan
true
false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [71]:
z= np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [75]:
z = np.ones((8,8))
z[::2, 1::2] = 0
z[1::2, ::2] = 0
print(z)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [131]:
arr = np.arange(336).reshape(6,7,8)
print(np.unravel_index(99,(6,7,8)))
result = np.where(arr == 99)
print(result)

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [81]:
z = np.tile([[0,1], [0,1]], (4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [9]:
import numpy as np
arr = np.array([50-100,100-100,150-100])
arr2 = np.array([100-100,100-100,100-100])
z = np.tile([arr, arr2], (2,2))
print(z)

[[-50   0  50 -50   0  50]
 [  0   0   0   0   0   0]
 [-50   0  50 -50   0  50]
 [  0   0   0   0   0   0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - mean) / std)

In [88]:
z = np.random.random((5,5))
z = (z - np.mean (z)) / (np.std (z))
print(z)

[[-1.57247644 -0.99532904  0.83993742  0.28771486  0.88840575]
 [-0.10816105  0.99906636  0.81280105  1.15546212  1.55226249]
 [-2.07280153 -0.25271496  0.38101952  0.07078514  1.59042977]
 [ 0.59528922 -0.06718368 -0.40183651  1.0092577  -0.30807687]
 [-0.8148419  -0.74944696 -1.01968759  0.07716529 -1.89704017]]


In [91]:
z.mean()


-2.042810365310288e-16

In [90]:
z.std()

0.9999999999999999

In [24]:
norm_z = (z-np.mean(z))/(np.std(z))
norm_z

array([[-0.23709911,  1.82467557,  1.04200929,  0.56488331, -1.01905371],
       [-1.01914002, -1.36950322,  1.52216525,  0.57367372,  0.95640937],
       [-1.5036896 ,  1.89336468,  1.40145369, -0.81751722, -0.92670866],
       [-0.92105645, -0.48865218,  0.30043311, -0.03168212, -0.5352181 ],
       [ 0.61209803, -1.07818578, -0.53194206, -0.26636415,  0.05464636]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [92]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\Igor\AppData\Local\Temp/ipykernel_7832/1857893590.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [112]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.matmul(x,y)
print(z)
t = np.dot(x,y)
print(t)

[[0.48011879 0.45302711]
 [0.85568055 1.04602966]
 [0.66119    0.58134508]
 [0.59912482 0.49439034]
 [0.76106571 0.93752478]]
[[0.48011879 0.45302711]
 [0.85568055 1.04602966]
 [0.66119    0.58134508]
 [0.59912482 0.49439034]
 [0.76106571 0.93752478]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [167]:
z = np.array([1,5,2,3,4,5,6,7,8,9,10,6])
print(z)
negated = (z > 3) & (z <= 8)
z[negated] *= -1
print(z)

[ 1  5  2  3  4  5  6  7  8  9 10  6]
[ 1 -5  2  3 -4 -5 -6 -7 -8  9 10 -6]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [175]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [200]:
import numpy as np
Z=np.array([3])
print(Z**Z) # power of
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[27]
[4]
[False]
[0.+3.j]
[3.]
[False]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [201]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Igor\AppData\Local\Temp/ipykernel_7832/1356192292.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Igor\AppData\Local\Temp/ipykernel_7832/1356192292.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [10]:
z = np.array([0.4, 1.5, 2.2, 3.1, 3.9])
print(np.ceil(z))

[1. 2. 3. 4. 4.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [4]:
x = np.arange(1,9)
y = np.arange(5,11)
print(x,y)
print(np.intersect1d(x,y))

[1 2 3 4 5 6 7 8] [ 5  6  7  8  9 10]
[5 6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [8]:
z = np.random.random(1000).reshape(10, 10, 10) * np.nan
np.seterr(all='ignore')
np.nanmedian(z, axis=[1, 2])

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [13]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [14]:
today = np.datetime64('2021-09-24', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(yesterday,'\n',today,'\n',tomorrow)

2021-09-23 
 2021-09-24 
 2021-09-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [15]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [16]:
x = np.array([1,2,3])
y = np.array([4,5,6])
res = np.multiply(    (np.add(x,y)),  (np.divide((x * -1), 2))    )
print(np.add(x,y))
print(x * -1)
print((np.divide((x * -1), 2)))
print(res)

[5 7 9]
[-1 -2 -3]
[-0.5 -1.  -1.5]
[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [28]:
x = np.array([-1.4, 1.8, 4, 5, 5.6, 6.1, 6.9, 7.3])
print(x)
print(np.trunc(x))
print(np.floor(x))
print(np.ceil(x))
print(np.rint(x))

[-1.4  1.8  4.   5.   5.6  6.1  6.9  7.3]
[-1.  1.  4.  5.  5.  6.  6.  7.]
[-2.  1.  4.  5.  5.  6.  6.  7.]
[-1.  2.  4.  5.  6.  7.  7.  8.]
[-1.  2.  4.  5.  6.  6.  7.  7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [43]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [54]:
z = (i for i in range(10))
np.fromiter(z, dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [58]:
np.linspace(0.1, 1, 10, endpoint=False)

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [67]:
z = np.random.random((1,10))
print(z)
print(np.sort(z))

[[0.95925264 0.92927994 0.53303487 0.89014918 0.86104387 0.54424395
  0.95119533 0.73172341 0.76618543 0.56024373]]
[[0.53303487 0.54424395 0.56024373 0.73172341 0.76618543 0.86104387
  0.89014918 0.92927994 0.95119533 0.95925264]]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [74]:
y = np.array([4,5,6])
# print(np.sum(y))
# print(np.ndarray.sum(y))
print(np.add.reduce(y))

15


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [78]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.equal(x,y))
print(np.array_equal(x,y))
print(np.allclose(x,y))

[False False False]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [82]:
x = np.array([1,2,3])
x.flags.writeable = False
x[0] = 5
print(x)

[1 2 3]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [92]:
z = np.random.random((10,2))
print(z, '\n')
x = z[:,0]
y = z[:,1]
print(x,'\n','\n',y,'\n')
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y,x)
print(r,'\n','\n',t)

[[0.05736914 0.93551762]
 [0.01796194 0.93398106]
 [0.25472954 0.86425507]
 [0.58226515 0.06749764]
 [0.66610026 0.29126121]
 [0.4856759  0.64962443]
 [0.75951896 0.1781198 ]
 [0.07951803 0.37027544]
 [0.7677773  0.95979037]
 [0.57536694 0.63940407]] 

[0.05736914 0.01796194 0.25472954 0.58226515 0.66610026 0.4856759
 0.75951896 0.07951803 0.7677773  0.57536694] 
 
 [0.93551762 0.93398106 0.86425507 0.06749764 0.29126121 0.64962443
 0.1781198  0.37027544 0.95979037 0.63940407] 

[0.937275   0.93415376 0.90101274 0.58616435 0.72699564 0.81110602
 0.78012545 0.3787176  1.22909704 0.8601655 ] 
 
 [1.5095496  1.55156711 1.28417324 0.11540741 0.41221176 0.92881652
 0.2303538  1.35925558 0.89609033 0.83806481]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [112]:
z = np.random.random(10)
print(z)
y = z.argmax()
z[y] = 0
print(z)

[0.19633177 0.4354161  0.38025373 0.29148365 0.75132829 0.33031442
 0.68492423 0.61883384 0.63517226 0.64817646]
[0.19633177 0.4354161  0.38025373 0.29148365 0.         0.33031442
 0.68492423 0.61883384 0.63517226 0.64817646]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [122]:
nx, ny = (3,2)
x = np.linspace(0,1, nx)
print(x)
y = np.linspace(0,1, ny)
print(y)
xv, yv = np.meshgrid(x,y)

print(xv)

[0.  0.5 1. ]
[0. 1.]
[[0.  0.5 1. ]
 [0.  0.5 1. ]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [129]:
x = [1,2,3,4]
y = [1,1,1]
c = 1 / np.subtract.outer(x,y)
print(c)

[[       inf        inf        inf]
 [1.         1.         1.        ]
 [0.5        0.5        0.5       ]
 [0.33333333 0.33333333 0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [141]:
x = np.iinfo(5)
print(x)
y = np.finfo(5.0)#.eps
print(y)

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------



#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [9]:
np.set_printoptions(precision=1)
z=np.array([1.123456789])
print(z)



[1.1]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [203]:
z = np.arange(10,20).reshape(2,5) +2
print(z)
print(np.argmin(z, axis=0))

[[12 13 14 15 16]
 [17 18 19 20 21]]
[0 0 0 0 0]


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray | np.unique)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)