## Remember that the solutions need to be saved int variable provided.

In [2]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [115]:
import numpy as np
sol1 = np.random.randint(100, size=(10, 10))
print(sol1)
print(np.amax(sol1))
print(np.amin(sol1))
# raise NotImplementedError()

[[21 18 43 42 40 41 31 52 54 10]
 [86  1 32 15  4 82 91 72  9 66]
 [62  8 43 20 77 23 98 45 96 46]
 [12 59 43  1 76 42 48 68 51 59]
 [41 93 86 47 61 45 29  6 24 34]
 [ 8 52 29 97 97 39 58 71  8 50]
 [29 98 10 62 95 98 30  7 28 32]
 [96 33 17 10 38 55 87 37 59 94]
 [16 38 64 72 69 27 86 41 32 81]
 [40  1 32 15 92 22 76  6 25 16]]
98
1


In [116]:
np.sort(sol1)

array([[10, 18, 21, 31, 40, 41, 42, 43, 52, 54],
       [ 1,  4,  9, 15, 32, 66, 72, 82, 86, 91],
       [ 8, 20, 23, 43, 45, 46, 62, 77, 96, 98],
       [ 1, 12, 42, 43, 48, 51, 59, 59, 68, 76],
       [ 6, 24, 29, 34, 41, 45, 47, 61, 86, 93],
       [ 8,  8, 29, 39, 50, 52, 58, 71, 97, 97],
       [ 7, 10, 28, 29, 30, 32, 62, 95, 98, 98],
       [10, 17, 33, 37, 38, 55, 59, 87, 94, 96],
       [16, 27, 32, 38, 41, 64, 69, 72, 81, 86],
       [ 1,  6, 15, 16, 22, 25, 32, 40, 76, 92]])

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [101]:
import numpy as np
sol2 = np.ones((10,10))
sol2[1:-1, 1:-1] = 0
print(sol2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**34. How to get all the dates corresponding to the month of July 2016**

In [107]:
import numpy as np
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

# print(sol3[0].dtype)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
assert sol3.shape == (31,)
assert type(sol3[0]) is np.datetime64

**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [119]:
sol41 = np.random.normal(size=(10, 10))
sol42 = np.random.uniform(size=(10, 10))
comparisson = sol41 == sol42
print(comparisson.all())

False


In [74]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [93]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])
sol5[[0, 1]] = sol5[[1, 0]]
print(sol5)

# raise NotImplementedError()

[[4 5 6]
 [1 2 3]]


In [ ]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [120]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
lists = []
total = 0
for i in range(len(arr)):
    total += arr[i:i+1]
    average = total / len(arr)
    lists.append(average)
    
reshape_array = np.array(lists).reshape(1, 10)
print(reshape_array)


[[0.1 0.3 0.6 1.  1.5 2.1 2.8 3.6 4.5 5.5]]


In [ ]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5