## Remember that the solutions need to be saved int variable provided.

In [2]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [51]:
import numpy as np
sol1 = np.random.rand(10, 10)
print(sol1)

# raise NotImplementedError()

[[0.15594628 0.78374232 0.30731307 0.4252078  0.88728615 0.23002178
  0.06773717 0.33741996 0.18242796 0.86313631]
 [0.22817063 0.9139036  0.40333199 0.84083618 0.84384652 0.07161984
  0.883704   0.04077174 0.60643912 0.38764435]
 [0.67905664 0.40646299 0.62898477 0.74101535 0.05099125 0.76065628
  0.249577   0.09016381 0.52296341 0.58900848]
 [0.14329721 0.3733392  0.46313306 0.79333765 0.27757653 0.83940906
  0.13502166 0.30083111 0.61864705 0.12693387]
 [0.83962898 0.25989417 0.89653993 0.5366024  0.72912918 0.17481421
  0.63533696 0.2057344  0.21539231 0.63799855]
 [0.47520592 0.09532809 0.211024   0.94069682 0.5855294  0.54093762
  0.16630894 0.17896099 0.1385452  0.34809641]
 [0.18185981 0.04138454 0.29438545 0.53028805 0.79873491 0.71010489
  0.95868711 0.42483103 0.26890692 0.77610401]
 [0.0203413  0.48482541 0.98011295 0.15596964 0.9054     0.24241913
  0.20584571 0.83043717 0.63639675 0.07550039]
 [0.46526379 0.57206605 0.43724993 0.37458477 0.82179407 0.19720453
  0.41417857

In [53]:
np.sort(sol1)

array([[0.06773717, 0.15594628, 0.18242796, 0.23002178, 0.30731307,
        0.33741996, 0.4252078 , 0.78374232, 0.86313631, 0.88728615],
       [0.04077174, 0.07161984, 0.22817063, 0.38764435, 0.40333199,
        0.60643912, 0.84083618, 0.84384652, 0.883704  , 0.9139036 ],
       [0.05099125, 0.09016381, 0.249577  , 0.40646299, 0.52296341,
        0.58900848, 0.62898477, 0.67905664, 0.74101535, 0.76065628],
       [0.12693387, 0.13502166, 0.14329721, 0.27757653, 0.30083111,
        0.3733392 , 0.46313306, 0.61864705, 0.79333765, 0.83940906],
       [0.17481421, 0.2057344 , 0.21539231, 0.25989417, 0.5366024 ,
        0.63533696, 0.63799855, 0.72912918, 0.83962898, 0.89653993],
       [0.09532809, 0.1385452 , 0.16630894, 0.17896099, 0.211024  ,
        0.34809641, 0.47520592, 0.54093762, 0.5855294 , 0.94069682],
       [0.04138454, 0.18185981, 0.26890692, 0.29438545, 0.42483103,
        0.53028805, 0.71010489, 0.77610401, 0.79873491, 0.95868711],
       [0.0203413 , 0.07550039, 0.1559696

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [27]:
#1 points
# sol2 = 0

# raise NotImplementedError()

In [54]:
import numpy as np
sol2 = np.ones((10,10))
sol2[1:-1, 1:-1] = 0
print(sol2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**34. How to get all the dates corresponding to the month of July 2016**

In [66]:
import numpy as np
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
assert sol3.shape == (31,)
assert type(sol3[0]) is np.datetime64

**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [77]:
#2 points
sol41 = np.random.normal(size=(10, 10))
sol42 = np.random.uniform(size=(10, 10))
comparisson = sol41 == sol42
print(comparisson.all())
# print(np.random.normal(size=(10, 10)))
# np.random.uniform(size=(10, 10))

False


In [74]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [93]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])
sol5[[0, 1]] = sol5[[1, 0]]
print(sol5)

# raise NotImplementedError()

[[4 5 6]
 [1 2 3]]


In [ ]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [97]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
sol6 = 0


In [ ]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5